language: python
python:
- '2.7'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
install: pip install -q -r requirements.txt
script:
- sphinx-build -b html -d _build/doctrees . _build/html
deploy:
- provider: s3
  access_key_id: $aws_key_prod
  secret_access_key: $aws_secret_prod
  bucket: vui-docs
  local-dir: _build/html
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
- provider: s3
  access_key_id: $aws_key_internal
  secret_access_key: $aws_secret_internal
  bucket: vui-docs-internal
  local-dir: _build/html
  upload-dir: ${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
env:
  global:
  - secure: ND6UvnWu7Fxmt0qjJyi1rMnb1YiulmV7g+fIK8q/t0Ah9NuKwf8rpSfq5o6NtekJpGkDUbiKXQgQTXLlE0SPGUfn0C17hRqEHao1pAVOHnKj/vd8hIa/IxGVEarjW3ccvTZZMuZjNHPYbmAmnnd/PXgKnIF1CwwDcHrFpjPraA0=
  - secure: GkKxfN1cc9UN4w/QNR6jJec3pB7mnIWH9oH/8PpRUI8lcOlAVbx9Nbfbkt8mdCoCJOMGsIwUz3aZgXeAglCMaWSBsIeVl6jsJJQK3sMz9ksTRcW9dr2bY7/wZyWWfGFfaw5M0vXE25jDWvFydVvIG5HkZRe+j8ixciffIPO9MLo=
  - secure: WSpWNAwbZ3HPuZREn5Egb/Yu13hxfu1SOp/VrUMBuNgtfkoDaQh6XRvF5ADvkSGU7/QnC+5tLPOGPw8mJ0dmCxM9iZYZdHieKkd2qKy85dv0Bz8mjE4W3dvF+wNoQ0qZ39jSc3HJFvlD+5ZNrfgC+TZzHKWsryYQlOpK1F1WsCk=
  - secure: BERjsO7xiTaAUePUT7gimjhbdAYtzjYtYt5v0Xdd2WR8CLe7ilKcrEWo7hM+LP8eyxJzIBw5pxGLaX5/fKuxLd8ajOqH2QlyG5HcOs7PRNT2/ec2OiSzrhwyHSguLzdGMwmvlBXzxBK11WEiElGm49VxFSboypUX3FBaA9nwlLw=
  - secure: CNcUnekzWxw7ak+lBKVYQK9dgTjB+iTBAmLJ+j2W6s7lIA+/6U9NPn8YCkmib8Ma2+/JsZnNGlqgCRysuXKEI7//Dp3SNUqf7mIWfblcPyqIPKtUV9VpblRPL07Dl35dBlSDYZLjHdzc5YkJ/WRgaB1Y7WWKTqYouLoqVCFN074=
after_success:
- python sendComment.py "Published to http://vui-docs-internal.s3-website-us-east-1.amazonaws.com/${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}"
